In [12]:
# -*- coding: utf-8 -*-
import random
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.optimizers import Adam
from keras.layers import Flatten,Dense
import cv2
import keras
#cv2.resize(s, (224,224))
#target_f=0
EPISODES = 1000

class DQNAgent:
    #def __init__(self, state_size, action_size):
    def __init__(self, action_size):
        #self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()

    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        vgg16_model=keras.applications.vgg16.VGG16()
        vgg16_model.layers.pop()
        model=keras.Sequential()
        for layer in vgg16_model.layers:
            model.add(layer)
        for layer in model.layers:
            layer.trainable=False
        model.add(Dense(32,activation="relu"))
        model.add(Dense(4,activation="linear"))
        model.compile(loss='mse',optimizer=Adam(lr=self.learning_rate))
        return model

    def memorize(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        state = np.expand_dims(state, axis=0)############
        act_values = self.model.predict(state)
        return np.argmax(act_values[0])  # returns action

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
                next_state = np.expand_dims(next_state, axis=0)#######
                target = (reward + self.gamma *
                          np.amax(self.model.predict(next_state)))
            state = np.expand_dims(state, axis=0)########################
            target_f = self.model.predict(state)
            print(target_f)
            target_f[0][action] = target
            print(target_f,"vishal",target)
            #np.reshape(target_f,(1,5))
            print(target_f,"Vishal Poddar")
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

    #def load(self, name):
    #    self.model.load_weights(name)

    def save(self, name):
        self.model.save_weights(name)

In [13]:
def car_action(temp):
    val=[0]*4
    val[temp]=1
    return [0.8*(val[0]-val[1]),val[2],val[3]]

In [14]:
if __name__ == "__main__":
    env = gym.make("CarRacing-v0")
    #state_size = env.observation_space.shape[0]
    #action_size = env.action_space.n
    action_size=4
    agent = DQNAgent(action_size)
    # agent.load("./save/cartpole-dqn.h5")
    done = False
    batch_size = 32

    for e in range(EPISODES):
        state = env.reset()
        state=cv2.resize(state, (224,224))
        #state = np.reshape(state, [1, state_size])
        for time in range(500):
            # env.render()
            a=agent.act(state)
            action = car_action(a)
            next_state, reward, done, _ = env.step(action)
            next_state=cv2.resize(next_state, (224,224))
            reward = reward if not done else -10
            #next_state = np.reshape(next_state, [1, state_size])
            agent.memorize(state, a, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}"
                      .format(e, EPISODES, time, agent.epsilon))
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        # if e % 10 == 0:
        #     agent.save("./save/cartpole-dqn.h5")

Track generation: 1282..1607 -> 325-tiles track
[[ 0.717928   1.0602539 -0.869491   0.6606239]]
[[ 0.717928   1.0602539 -0.869491   6.9723988]] vishal 6.972398592734042
[[ 0.717928   1.0602539 -0.869491   6.9723988]] Vishal Poddar
[[ 1.2089401  -0.11046309  0.41048673  3.023284  ]]
[[ 2.3505123  -0.11046309  0.41048673  3.023284  ]] vishal 2.3505122780799863
[[ 2.3505123  -0.11046309  0.41048673  3.023284  ]] Vishal Poddar
[[ 3.647333   1.2551079 -1.0150247  5.733023 ]]
[[3.647333  1.2551079 3.4823909 5.733023 ]] vishal 3.482390797138214
[[3.647333  1.2551079 3.4823909 5.733023 ]] Vishal Poddar
[[ 5.3719134e+00 -1.8755421e-03  1.7257473e+00  6.7799621e+00]]
[[ 5.3719134e+00 -1.8755421e-03  1.7257473e+00  6.8373270e+00]] vishal 6.837327218055725
[[ 5.3719134e+00 -1.8755421e-03  1.7257473e+00  6.8373270e+00]] Vishal Poddar
[[6.975323  1.2663035 2.2346926 9.724877 ]]
[[8.02525   1.2663035 2.2346926 9.724877 ]] vishal 8.025250768661499
[[8.02525   1.2663035 2.2346926 9.724877 ]] Vishal Pod

[[21.730534 21.809536 20.811438 22.367083]]
[[22.519312 21.809536 20.811438 22.367083]] vishal 22.51931285858154
[[22.519312 21.809536 20.811438 22.367083]] Vishal Poddar
[[22.515    20.805882 19.441717 19.811472]]
[[21.818184 20.805882 19.441717 19.811472]] vishal 21.818183040618898
[[21.818184 20.805882 19.441717 19.811472]] Vishal Poddar
[[20.752903 21.314795 20.319147 22.278595]]
[[20.752903 21.314795 20.319147 21.489939]] vishal 21.489939022064206
[[20.752903 21.314795 20.319147 21.489939]] Vishal Poddar
[[22.58638  23.573423 21.645592 24.154554]]
[[21.177858 23.573423 21.645592 24.154554]] vishal 21.177857875823975
[[21.177858 23.573423 21.645592 24.154554]] Vishal Poddar
[[20.047367 20.229876 16.559374 22.521624]]
[[21.344229 20.229876 16.559374 22.521624]] vishal 21.34422855377197
[[21.344229 20.229876 16.559374 22.521624]] Vishal Poddar
[[20.707481 20.537306 17.209219 22.73894 ]]
[[23.157053 20.537306 17.209219 22.73894 ]] vishal 23.15705232620239
[[23.157053 20.537306 17.2092

[[23.725119 21.493532 23.670427 20.505953]]
[[23.725119 22.294128 23.670427 20.505953]] vishal 22.294128894805905
[[23.725119 22.294128 23.670427 20.505953]] Vishal Poddar
[[22.155537 20.139805 21.602694 17.782845]]
[[22.155537 20.139805 22.911888 17.782845]] vishal 22.911887645721436
[[22.155537 20.139805 22.911888 17.782845]] Vishal Poddar
[[20.894766 19.503616 22.455702 18.498573]]
[[20.894766 22.005611 22.455702 18.498573]] vishal 22.00561075210571
[[20.894766 22.005611 22.455702 18.498573]] Vishal Poddar
[[21.623144 19.585342 22.442661 18.874958]]
[[21.623144 19.585342 21.701357 18.874958]] vishal 21.70135736465454
[[21.623144 19.585342 21.701357 18.874958]] Vishal Poddar
[[20.901983 20.037085 18.868639 16.439827]]
[[20.901983 20.037085 18.868639 20.912516]] vishal 20.912514972686765
[[20.901983 20.037085 18.868639 20.912516]] Vishal Poddar
[[22.126488 20.98631  22.894339 20.179356]]
[[22.126488 20.98631  22.894339 20.258104]] vishal 20.258103466033937
[[22.126488 20.98631  22.894

[[22.000486 20.660078 21.877726 19.026342]]
[[22.000486 20.660078 21.877726 20.094309]] vishal 20.094309425354005
[[22.000486 20.660078 21.877726 20.094309]] Vishal Poddar
[[23.023785 21.231388 22.762167 20.692144]]
[[22.325825 21.231388 22.762167 20.692144]] vishal 22.325824069976804
[[22.325825 21.231388 22.762167 20.692144]] Vishal Poddar
[[22.004736 21.045145 21.944277 19.38074 ]]
[[22.004736 20.747227 21.944277 19.38074 ]] vishal 20.747226047515866
[[22.004736 20.747227 21.944277 19.38074 ]] Vishal Poddar
[[19.286312 19.503492 20.047241 18.186426]]
[[19.286312 19.503492 20.047241 20.09377 ]] vishal 20.093769454956053
[[19.286312 19.503492 20.047241 20.09377 ]] Vishal Poddar
[[23.61669  23.079735 22.406027 20.446802]]
[[23.61669  21.730349 22.406027 20.446802]] vishal 21.73034906387329
[[23.61669  21.730349 22.406027 20.446802]] Vishal Poddar
[[21.72054  21.080484 21.643505 20.014917]]
[[20.74431  21.080484 21.643505 20.014917]] vishal 20.744310569763186
[[20.74431  21.080484 21.64

[[13.053239 13.164509 15.620137 14.187717]]
[[13.78577  13.164509 15.620137 14.187717]] vishal 13.785770034790039
[[13.78577  13.164509 15.620137 14.187717]] Vishal Poddar
[[15.589045 13.23064  15.744345 14.412372]]
[[15.589045 13.23064  15.744345 13.955413]] vishal 13.955413150787352
[[15.589045 13.23064  15.744345 13.955413]] Vishal Poddar
[[15.309845 12.893727 15.662402 13.584503]]
[[15.309845 12.893727 15.056147 13.584503]] vishal 15.056146430969237
[[15.309845 12.893727 15.056147 13.584503]] Vishal Poddar
[[16.021894  13.0287075 16.096443  14.475423 ]]
[[16.021894  13.0287075 14.600233  14.475423 ]] vishal 14.600232934951782
[[16.021894  13.0287075 14.600233  14.475423 ]] Vishal Poddar
[[15.506226 12.665623 15.818039 13.77816 ]]
[[14.88308  12.665623 15.818039 13.77816 ]] vishal 14.883079576492309
[[14.88308  12.665623 15.818039 13.77816 ]] Vishal Poddar
[[15.118042 14.217408 14.480257 13.963946]]
[[15.118042 14.780762 14.480257 13.963946]] vishal 14.780761528015136
[[15.118042 14

[[13.183194 13.907547 14.246024 13.793637]]
[[13.183194 13.907547 14.36017  13.793637]] vishal 14.360169887542725
[[13.183194 13.907547 14.36017  13.793637]] Vishal Poddar
[[11.451224  13.46987   12.3435755 14.114973 ]]
[[11.451224  13.46987   12.3435755 13.391534 ]] vishal 13.39153366088867
[[11.451224  13.46987   12.3435755 13.391534 ]] Vishal Poddar
[[11.1529255 13.155368  11.559062  13.112045 ]]
[[12.548272 13.155368 11.559062 13.112045]] vishal 12.548272037506104
[[12.548272 13.155368 11.559062 13.112045]] Vishal Poddar
[[21.320002 19.242058 12.834752 24.869623]]
[[21.320002 19.242058 12.834752 23.046532]] vishal 23.04653234481811
[[21.320002 19.242058 12.834752 23.046532]] Vishal Poddar
[[16.768343 16.530533 16.131804 16.79075 ]]
[[16.768343 14.847339 16.131804 16.79075 ]] vishal 14.847338247299193
[[16.768343 14.847339 16.131804 16.79075 ]] Vishal Poddar
[[13.737886 14.746258 15.116054 15.41329 ]]
[[13.737886 14.746258 15.116054 14.597418]] vishal 14.597418022155761
[[13.737886 

[[12.5151825 13.613092  12.871549  12.719447 ]]
[[13.651413 13.613092 12.871549 12.719447]] vishal 13.651412534713744
[[13.651413 13.613092 12.871549 12.719447]] Vishal Poddar
[[13.171081 14.381227 12.042147 14.271171]]
[[13.82074  14.381227 12.042147 14.271171]] vishal 13.820739459991454
[[13.82074  14.381227 12.042147 14.271171]] Vishal Poddar
[[14.058053 16.29584  11.204057 14.846157]]
[[15.680664 16.29584  11.204057 14.846157]] vishal 15.680663871765136
[[15.680664 16.29584  11.204057 14.846157]] Vishal Poddar
[[11.77639  12.782454 12.129335 11.721117]]
[[11.77639  12.782454 12.368333 11.721117]] vishal 12.36833324432373
[[11.77639  12.782454 12.368333 11.721117]] Vishal Poddar
[[14.128704  13.776762  13.171149  12.5137825]]
[[13.826071  13.776762  13.171149  12.5137825]] vishal 13.826070308685303
[[13.826071  13.776762  13.171149  12.5137825]] Vishal Poddar
[[13.436841 13.730424 12.665977 12.779229]]
[[12.940994 13.730424 12.665977 12.779229]] vishal 12.940994501113892
[[12.940994

[[24.638245 18.74354  22.884907 20.224674]]
[[23.37388  18.74354  22.884907 20.224674]] vishal 23.373881244659422
[[23.37388  18.74354  22.884907 20.224674]] Vishal Poddar
[[28.618567 23.843506 24.625746 25.776426]]
[[28.618567 23.843506 27.284357 25.776426]] vishal 27.28435773849487
[[28.618567 23.843506 27.284357 25.776426]] Vishal Poddar
[[27.077013 21.905668 26.053993 25.142439]]
[[25.44981  21.905668 26.053993 25.142439]] vishal 25.449810123443605
[[25.44981  21.905668 26.053993 25.142439]] Vishal Poddar
[[34.56948  30.306398 28.129053 30.667465]]
[[32.910343 30.306398 28.129053 30.667465]] vishal 32.9103437423706
[[32.910343 30.306398 28.129053 30.667465]] Vishal Poddar
[[27.017962 22.392147 27.657661 26.378971]]
[[27.017962 22.392147 27.74265  26.378971]] vishal 27.742649459838866
[[27.017962 22.392147 27.74265  26.378971]] Vishal Poddar
[[29.210949 25.118492 29.554605 29.253555]]
[[29.970898 25.118492 29.554605 29.253555]] vishal 29.970897102355956
[[29.970898 25.118492 29.5546

[[41.672897 44.077057 41.11484  41.49762 ]]
[[43.606083 44.077057 41.11484  41.49762 ]] vishal 43.60608463287353
[[43.606083 44.077057 41.11484  41.49762 ]] Vishal Poddar
[[45.677612 46.273537 43.584957 41.96213 ]]
[[45.677612 43.77236  43.584957 41.96213 ]] vishal 43.77236289978027
[[45.677612 43.77236  43.584957 41.96213 ]] Vishal Poddar
[[46.091545 46.77904  41.90037  43.19269 ]]
[[46.091545 46.77904  41.90037  43.10768 ]] vishal 43.107681083679196
[[46.091545 46.77904  41.90037  43.10768 ]] Vishal Poddar
[[47.24935  47.868702 42.23544  43.867977]]
[[46.53555  47.868702 42.23544  43.867977]] vishal 46.535550880432126
[[46.53555  47.868702 42.23544  43.867977]] Vishal Poddar
[[46.90481  45.510105 42.078403 42.005177]]
[[43.9637   45.510105 42.078403 42.005177]] vishal 43.96370086669921
[[43.9637   45.510105 42.078403 42.005177]] Vishal Poddar
[[47.952427 50.278168 43.095116 45.81612 ]]
[[47.952427 46.843735 43.095116 45.81612 ]] vishal 46.84373626708984
[[47.952427 46.843735 43.09511

[[34.85947  33.43079  34.682495 27.877724]]
[[34.85947  33.43079  33.44807  27.877724]] vishal 33.44807090759277
[[34.85947  33.43079  33.44807  27.877724]] Vishal Poddar
[[34.696255 32.953243 34.671497 26.838425]]
[[34.696255 32.953243 35.09859  26.838425]] vishal 35.09859008789062
[[34.696255 32.953243 35.09859  26.838425]] Vishal Poddar
[[39.471603 35.715343 36.707676 25.625498]]
[[39.471603 38.382797 36.707676 25.625498]] vishal 38.38279876708984
[[39.471603 38.382797 36.707676 25.625498]] Vishal Poddar
[[32.58518  34.430805 32.87957  30.016142]]
[[32.58518  32.80952  32.87957  30.016142]] vishal 32.809521484375
[[32.58518  32.80952  32.87957  30.016142]] Vishal Poddar
[[35.975246 33.533993 30.164995 21.734968]]
[[35.36068  33.533993 30.164995 21.734968]] vishal 35.36067867279053
[[35.36068  33.533993 30.164995 21.734968]] Vishal Poddar
[[41.56412  39.220627 37.664665 27.315214]]
[[41.56412  39.220627 37.664665 39.02559 ]] vishal 39.025588226318355
[[41.56412  39.220627 37.664665 3

[[78.18453 79.55526 83.17149 75.37431]]
[[78.18453  87.284615 83.17149  75.37431 ]] vishal 87.28461265563965
[[78.18453  87.284615 83.17149  75.37431 ]] Vishal Poddar
[[83.01384  78.88019  86.405495 70.66756 ]]
[[83.01384  78.88019  86.405495 77.5669  ]] vishal 77.56689949035645
[[83.01384  78.88019  86.405495 77.5669  ]] Vishal Poddar
[[83.25401  81.079315 87.146416 71.54781 ]]
[[83.25401  83.10337  87.146416 71.54781 ]] vishal 83.10337181091309
[[83.25401  83.10337  87.146416 71.54781 ]] Vishal Poddar
[[90.697296 93.60913  98.02068  81.98428 ]]
[[90.697296 93.60913  98.02068  84.75698 ]] vishal 84.75697860717774
[[90.697296 93.60913  98.02068  84.75698 ]] Vishal Poddar
[[77.761536 79.898865 78.74907  68.87631 ]]
[[76.33224  79.898865 78.74907  68.87631 ]] vishal 76.33223724365234
[[76.33224  79.898865 78.74907  68.87631 ]] Vishal Poddar
[[72.61796 84.70316 71.09539 71.0948 ]]
[[83.82685 84.70316 71.09539 71.0948 ]] vishal 83.8268524169922
[[83.82685 84.70316 71.09539 71.0948 ]] Visha

[[75.28318  73.33191  83.129906 78.147835]]
[[75.28318  73.33191  83.129906 81.46781 ]] vishal 81.4678123474121
[[75.28318  73.33191  83.129906 81.46781 ]] Vishal Poddar
[[ 92.840294  93.444275 102.14068   96.480194]]
[[ 92.840294  93.444275 102.14068   91.06401 ]] vishal 91.06401405334474
[[ 92.840294  93.444275 102.14068   91.06401 ]] Vishal Poddar
[[80.90401  75.66271  88.52068  78.897995]]
[[80.90401  75.66271  85.77996  78.897995]] vishal 85.77995796203614
[[80.90401  75.66271  85.77996  78.897995]] Vishal Poddar
[[81.97695 80.47994 90.21257 82.58027]]
[[80.244484 80.47994  90.21257  82.58027 ]] vishal 80.24448585510254
[[80.244484 80.47994  90.21257  82.58027 ]] Vishal Poddar
[[ 93.49153  97.58875 102.1295   97.27296]]
[[ 94.87297  97.58875 102.1295   97.27296]] vishal 94.87297248840332
[[ 94.87297  97.58875 102.1295   97.27296]] Vishal Poddar
[[88.961205 91.20044  96.48612  89.353836]]
[[88.961205 91.20044  99.19681  89.353836]] vishal 99.19680869961962
[[88.961205 91.20044  99.

[[59.288486 53.71687  61.76515  53.29711 ]]
[[59.288486 53.71687  59.583355 53.29711 ]] vishal 59.58335571289062
[[59.288486 53.71687  59.583355 53.29711 ]] Vishal Poddar
[[52.47762  50.946697 56.556416 51.412323]]
[[52.47762  50.946697 56.556416 55.066383]] vishal 55.06638374328613
[[52.47762  50.946697 56.556416 55.066383]] Vishal Poddar
[[76.684975 76.21593  79.99243  71.93507 ]]
[[76.684975 76.21593  77.937904 71.93507 ]] vishal 77.93790626525879
[[76.684975 76.21593  77.937904 71.93507 ]] Vishal Poddar
[[53.985416 50.807938 57.641186 50.60258 ]]
[[53.985416 50.807938 56.29541  50.60258 ]] vishal 56.295410728454584
[[53.985416 50.807938 56.29541  50.60258 ]] Vishal Poddar
[[75.86471  75.444305 79.49162  72.59079 ]]
[[75.86471  75.444305 79.319214 72.59079 ]] vishal 79.31921577453613
[[75.86471  75.444305 79.319214 72.59079 ]] Vishal Poddar
[[67.40552 66.53082 67.8542  65.2564 ]]
[[67.4439  66.53082 67.8542  65.2564 ]] vishal 67.44390411376953
[[67.4439  66.53082 67.8542  65.2564 ]]

[[56.41078  58.46663  45.341633 54.84027 ]]
[[55.51349  58.46663  45.341633 54.84027 ]] vishal 55.51349010467529
[[55.51349  58.46663  45.341633 54.84027 ]] Vishal Poddar
[[33.4605   34.035942 34.912373 34.77281 ]]
[[33.769707 34.035942 34.912373 34.77281 ]] vishal 33.769708442687985
[[33.769707 34.035942 34.912373 34.77281 ]] Vishal Poddar
[[32.259144 31.273302 34.056396 31.991245]]
[[32.259144 31.273302 33.381367 31.991245]] vishal 33.38136825561523
[[32.259144 31.273302 33.381367 31.991245]] Vishal Poddar
[[39.385517 38.138737 40.330505 37.714493]]
[[39.385517 38.138737 35.791637 37.714493]] vishal 35.79163665771484
[[39.385517 38.138737 35.791637 37.714493]] Vishal Poddar
[[51.651695 55.66422  52.52425  53.170963]]
[[52.92006  55.66422  52.52425  53.170963]] vishal 52.92005939483642
[[52.92006  55.66422  52.52425  53.170963]] Vishal Poddar
[[30.76719  31.310831 31.526049 31.74369 ]]
[[30.76719  31.505312 31.526049 31.74369 ]] vishal 31.505311775207517
[[30.76719  31.505312 31.52604

[[21.217094 23.737358 22.538717 24.584087]]
[[21.217094 23.317953 22.538717 24.584087]] vishal 23.317952632904053
[[21.217094 23.317953 22.538717 24.584087]] Vishal Poddar
[[40.95032  45.871964 43.43702  42.552406]]
[[40.95032  44.90869  43.43702  42.552406]] vishal 44.908692550659175
[[40.95032  44.90869  43.43702  42.552406]] Vishal Poddar
[[28.863235 26.836248 28.12278  28.355993]]
[[28.863235 27.850933 28.12278  28.355993]] vishal 27.850933456420897
[[28.863235 27.850933 28.12278  28.355993]] Vishal Poddar
[[44.113537 47.555046 47.95214  43.27995 ]]
[[44.113537 47.555046 47.95214  43.47    ]] vishal 43.470001220703125
[[44.113537 47.555046 47.95214  43.47    ]] Vishal Poddar
[[19.2065   21.799221 21.06169  24.060135]]
[[19.2065   21.799221 21.06169  22.556757]] vishal 22.55675745010376
[[19.2065   21.799221 21.06169  22.556757]] Vishal Poddar
[[37.63767  39.11033  37.014076 38.523605]]
[[38.827404 39.11033  37.014076 38.523605]] vishal 38.82740459442138
[[38.827404 39.11033  37.014

[[31.42545  32.595264 32.57429  34.35122 ]]
[[31.42545  32.595264 32.57429  35.1265  ]] vishal 35.126498222351074
[[31.42545  32.595264 32.57429  35.1265  ]] Vishal Poddar
[[30.515694 31.060396 31.080069 31.774734]]
[[31.94338  31.060396 31.080069 31.774734]] vishal 31.94337997436523
[[31.94338  31.060396 31.080069 31.774734]] Vishal Poddar
[[41.22814  47.815773 46.46303  44.594986]]
[[45.80615  47.815773 46.46303  44.594986]] vishal 45.80614871978759
[[45.80615  47.815773 46.46303  44.594986]] Vishal Poddar
[[22.47327  21.452759 22.824883 21.30721 ]]
[[22.47327  21.452759 22.824883 21.550726]] vishal 21.550725555419923
[[22.47327  21.452759 22.824883 21.550726]] Vishal Poddar
[[21.947659 21.850336 22.34605  22.030247]]
[[21.947659 21.317354 22.34605  22.030247]] vishal 21.31735506057739
[[21.947659 21.317354 22.34605  22.030247]] Vishal Poddar
[[40.187286 45.479244 42.80339  42.527573]]
[[40.187286 45.62035  42.80339  42.527573]] vishal 45.62034816741943
[[40.187286 45.62035  42.80339

[[32.74435  28.128794 31.95382  29.264528]]
[[32.66576  28.128794 31.95382  29.264528]] vishal 32.66575889587402
[[32.66576  28.128794 31.95382  29.264528]] Vishal Poddar
[[24.483027 21.318775 24.28589  22.513006]]
[[24.483027 21.549023 24.28589  22.513006]] vishal 21.54902229309082
[[24.483027 21.549023 24.28589  22.513006]] Vishal Poddar
[[25.319435 22.48181  25.057436 22.543774]]
[[25.319435 22.48181  23.01423  22.543774]] vishal 23.014230155944823
[[25.319435 22.48181  23.01423  22.543774]] Vishal Poddar
[[28.507132 30.704233 26.425854 29.557556]]
[[26.670282 30.704233 26.425854 29.557556]] vishal 26.670282745361327
[[26.670282 30.704233 26.425854 29.557556]] Vishal Poddar
[[36.530926 41.603535 40.76999  39.527367]]
[[36.530926 41.078495 40.76999  39.527367]] vishal 41.07849407196045
[[36.530926 41.078495 40.76999  39.527367]] Vishal Poddar
[[21.007998 23.722496 22.674849 25.119436]]
[[23.285374 23.722496 22.674849 25.119436]] vishal 23.285373210906982
[[23.285374 23.722496 22.6748

[[26.883228 25.381361 25.80466  27.96913 ]]
[[26.883228 26.93189  25.80466  27.96913 ]] vishal 26.931891155242916
[[26.883228 26.93189  25.80466  27.96913 ]] Vishal Poddar
[[44.783634 42.773163 42.495613 44.960045]]
[[44.783634 42.773163 42.495613 43.36608 ]] vishal 43.36608047485351
[[44.783634 42.773163 42.495613 43.36608 ]] Vishal Poddar
[[38.279335 36.626923 35.599976 41.42733 ]]
[[38.279335 36.626923 40.080612 41.42733 ]] vishal 40.08061065673828
[[38.279335 36.626923 40.080612 41.42733 ]] Vishal Poddar
[[41.585823 39.62771  38.88262  43.841816]]
[[41.39467  39.62771  38.88262  43.841816]] vishal 41.39467029571533
[[41.39467  39.62771  38.88262  43.841816]] Vishal Poddar
[[43.789207 44.098675 44.033375 44.39207 ]]
[[43.789207 44.098675 44.033375 41.073875]] vishal 41.07387714385986
[[43.789207 44.098675 44.033375 41.073875]] Vishal Poddar
[[33.382374 29.239021 32.46655  31.153135]]
[[33.382374 29.239021 32.46655  31.23521 ]] vishal 31.23521060943603
[[33.382374 29.239021 32.46655 

[[39.247456 39.959904 41.779686 37.53985 ]]
[[39.247456 39.959904 40.3456   37.53985 ]] vishal 40.345598411560054
[[39.247456 39.959904 40.3456   37.53985 ]] Vishal Poddar
[[28.963486 27.465744 28.923729 27.158865]]
[[28.963486 27.239672 28.923729 27.158865]] vishal 27.23967247009277
[[28.963486 27.239672 28.923729 27.158865]] Vishal Poddar
[[40.47274  40.97799  42.048367 38.991936]]
[[41.30892  40.97799  42.048367 38.991936]] vishal 41.30892009735107
[[41.30892  40.97799  42.048367 38.991936]] Vishal Poddar
[[43.103294 43.95519  44.35681  41.49742 ]]
[[41.649788 43.95519  44.35681  41.49742 ]] vishal 41.649786376953124
[[41.649788 43.95519  44.35681  41.49742 ]] Vishal Poddar
[[26.750929 29.19741  25.825407 26.619074]]
[[26.56437  29.19741  25.825407 26.619074]] vishal 26.56436882019043
[[26.56437  29.19741  25.825407 26.619074]] Vishal Poddar
[[40.338406 39.4746   42.0378   37.64268 ]]
[[40.38124 39.4746  42.0378  37.64268]] vishal 40.381240081787105
[[40.38124 39.4746  42.0378  37.6

[[26.55555  27.580685 25.757303 28.905378]]
[[26.55555  27.580685 25.757303 28.228708]] vishal 28.228707981109615
[[26.55555  27.580685 25.757303 28.228708]] Vishal Poddar
[[38.505314 39.24192  36.451283 38.54007 ]]
[[38.505314 38.85775  36.451283 38.54007 ]] vishal 38.85774803161621
[[38.505314 38.85775  36.451283 38.54007 ]] Vishal Poddar
[[35.50758  31.986095 32.50809  32.280716]]
[[34.228954 31.986095 32.50809  32.280716]] vishal 34.228955078125
[[34.228954 31.986095 32.50809  32.280716]] Vishal Poddar
[[35.44817  34.477104 34.064667 37.37123 ]]
[[35.44817  34.477104 35.87831  37.37123 ]] vishal 35.878310966491696
[[35.44817  34.477104 35.87831  37.37123 ]] Vishal Poddar
[[35.426674 34.083878 33.753925 35.95967 ]]
[[35.458424 34.083878 33.753925 35.95967 ]] vishal 35.45842418670654
[[35.458424 34.083878 33.753925 35.95967 ]] Vishal Poddar
[[38.65133  39.289993 37.714794 37.657238]]
[[38.65133  39.289993 37.714794 37.744217]] vishal 37.744216728210446
[[38.65133  39.289993 37.714794

[[31.951265 34.986137 34.350475 32.61428 ]]
[[31.865215 34.986137 34.350475 32.61428 ]] vishal 31.86521472930908
[[31.865215 34.986137 34.350475 32.61428 ]] Vishal Poddar
[[32.373714 32.356724 33.5141   31.539701]]
[[32.373714 32.356724 33.5141   30.753433]] vishal 30.75343379974365
[[32.373714 32.356724 33.5141   30.753433]] Vishal Poddar
[[23.663124 21.292923 22.800352 20.4506  ]]
[[23.663124 21.470034 22.800352 20.4506  ]] vishal 21.470034408569333
[[23.663124 21.470034 22.800352 20.4506  ]] Vishal Poddar
[[29.881706 30.672714 31.414522 28.404757]]
[[29.881706 30.672714 29.828516 28.404757]] vishal 29.82851524353027
[[29.881706 30.672714 29.828516 28.404757]] Vishal Poddar
[[30.522282 31.526377 32.034588 29.264221]]
[[30.67447  31.526377 32.034588 29.264221]] vishal 30.674471282958983
[[30.67447  31.526377 32.034588 29.264221]] Vishal Poddar
[[29.600151 30.388094 31.052347 27.915253]]
[[29.600151 30.749067 31.052347 27.915253]] vishal 30.74906692504883
[[29.600151 30.749067 31.05234

[[24.792076 23.032806 23.772148 23.715538]]
[[24.792076 23.514196 23.772148 23.715538]] vishal 23.514195632934566
[[24.792076 23.514196 23.772148 23.715538]] Vishal Poddar
[[25.470863 24.719246 25.624052 27.701508]]
[[25.470863 24.719246 26.477037 27.701508]] vishal 26.477036762237546
[[25.470863 24.719246 26.477037 27.701508]] Vishal Poddar
[[19.95436  16.927723 19.139763 17.752956]]
[[19.95436  17.89482  19.139763 17.752956]] vishal 17.894819736480713
[[19.95436  17.89482  19.139763 17.752956]] Vishal Poddar
[[25.975693 27.532059 27.148222 26.764729]]
[[24.354866 27.532059 27.148222 26.764729]] vishal 24.35486612319946
[[24.354866 27.532059 27.148222 26.764729]] Vishal Poddar
[[26.005362 28.0405   27.770655 27.544477]]
[[26.005362 28.0405   27.770655 26.343407]] vishal 26.343406772613523
[[26.005362 28.0405   27.770655 26.343407]] Vishal Poddar
[[26.940104 28.722351 28.880981 27.503931]]
[[26.940104 28.722351 27.559977 27.503931]] vishal 27.559976387023923
[[26.940104 28.722351 27.55

[[21.39322  18.574747 19.956934 18.45293 ]]
[[21.39322  18.574747 20.921814 18.45293 ]] vishal 20.921814060211183
[[21.39322  18.574747 20.921814 18.45293 ]] Vishal Poddar
[[22.265175 19.181892 20.730574 19.164513]]
[[22.265175 19.181892 20.730574 21.060133]] vishal 21.060133457183838
[[22.265175 19.181892 20.730574 21.060133]] Vishal Poddar
[[23.6841   23.111862 22.923668 23.90902 ]]
[[23.6841   23.91572  22.923668 23.90902 ]] vishal 23.915719795227048
[[23.6841   23.91572  22.923668 23.90902 ]] Vishal Poddar
[[19.462158 16.391075 17.286236 15.75874 ]]
[[19.462158 16.391075 18.03302  15.75874 ]] vishal 18.033019542694092
[[19.462158 16.391075 18.03302  15.75874 ]] Vishal Poddar
[[22.194723 21.85169  21.780128 21.800146]]
[[21.180555 21.85169  21.780128 21.800146]] vishal 21.180555915832517
[[21.180555 21.85169  21.780128 21.800146]] Vishal Poddar
[[22.638327 19.357779 21.25466  19.803324]]
[[22.638327 19.357779 22.731201 19.803324]] vishal 22.731200504302976
[[22.638327 19.357779 22.7

[[15.667383 16.927357 16.87335  15.948174]]
[[15.667383 16.364649 16.87335  15.948174]] vishal 16.364648723602294
[[15.667383 16.364649 16.87335  15.948174]] Vishal Poddar
[[18.389244 18.835192 18.833843 19.141161]]
[[18.389244 18.835192 18.833843 17.461355]] vishal 17.461355781555174
[[18.389244 18.835192 18.833843 17.461355]] Vishal Poddar
[[19.322037 18.516102 19.446295 18.998848]]
[[18.20458  18.516102 19.446295 18.998848]] vishal 18.204579734802245
[[18.20458  18.516102 19.446295 18.998848]] Vishal Poddar
[[15.939288 15.37099  16.803709 14.776789]]
[[15.939288 15.37099  15.609802 14.776789]] vishal 15.609802722930908
[[15.939288 15.37099  15.609802 14.776789]] Vishal Poddar
[[13.841975 14.703893 14.46396  14.244689]]
[[13.841975  14.703893  13.8375635 14.244689 ]] vishal 13.837563705444335
[[13.841975  14.703893  13.8375635 14.244689 ]] Vishal Poddar
[[15.319953 14.656273 16.324453 13.497028]]
[[15.319953 14.656273 16.324453 15.255912]] vishal 15.255911922454834
[[15.319953 14.656

KeyboardInterrupt: 

In [17]:
 for e in range(10):
        state = env.reset()
        state=cv2.resize(next_state, (224,224))
        #state = np.reshape(state, [1, state_size])
        
        for time in range(500):
            env.render()
            action = agent.act(state)
            action = car_action(action)
            next_state, reward, done, _ = env.step(action)
            next_state=cv2.resize(next_state, (224,224))
            reward = reward if not done else -10
            #next_state = np.reshape(next_state, [1, state_size])
            #agent.memorize(state, action, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}"
                      .format(e, EPISODES, time, agent.epsilon))
                break

Track generation: 1211..1525 -> 314-tiles track
Track generation: 999..1258 -> 259-tiles track


KeyboardInterrupt: 

In [81]:
agent.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)      

In [18]:
env.close()